package: iconpicker
version: '2.0.0'
author: 'FriendsOfRedaxo'
supportpage: https://github.com/friendsofredaxo/iconpicker


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.17

page:
    title: translate:iconpicker_title
    hidden: true
